from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from FormPage import FormPage
def test_form_page():
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
    formpage = FormPage(driver)
    formpage.input_firstname('Иван')
    formpage.input_lastname('Петров')
    formpage.input_address('Ленина, 55-3')
    formpage.input_email('test@skypro.com')
    formpage.input_phone(+7985899998787)
    formpage.input_city('Москва')
    formpage.input_country('Россия')
    formpage.input_job('QA')
    formpage.input_company('SkyPro')
    formpage.submit()
    zip_code_element = formpage.zip_code()
    first_name_element = formpage.first_name()
    last_name_element = formpage.last_name()
    address_element = formpage.address()
    email_element = formpage.email()
    phone_element = formpage.phone()
    city_element = formpage.city()
    country_element = formpage.country()
    job_element = formpage.job()
    company_element = formpage.company()
    assert "alert py-2 alert-danger" in zip_code_element.get_attribute("class")
    assert "alert py-2 alert-success" in first_name_element.get_attribute("class")
    assert "alert py-2 alert-success" in last_name_element.get_attribute("class")
    assert "alert py-2 alert-success" in address_element.get_attribute("class")
    assert "alert py-2 alert-success" in email_element.get_attribute("class")
    assert "alert py-2 alert-success" in phone_element.get_attribute("class")
    assert "alert py-2 alert-success" in city_element.get_attribute("class")
    assert "alert py-2 alert-success" in country_element.get_attribute("class")
    assert "alert py-2 alert-success" in job_element.get_attribute("class")
    assert "alert py-2 alert-success" in company_element.get_attribute("class")
    driver.quit()
    